### PR TITLE
Minor Fixes and Features

### PR DESCRIPTION
**Pull request by Aenima4six2**
netstandard2.0
use sync udp client (prevent chunking timeouts)
add non periodic batch sink

### CODE REVIEW

**Comment by justmara** [comment]
>use sync udp client (prevent chunking timeouts)

Hi. Could you please comment on this? What does that mean? What problem did you solve with this?

**Comment by Aenima4six2** [comment]
netcore 2.0 supports async and synchronous UDP send methods on the UDPClient. It was observed that under extreme traffic/load on netcore web apps, calling the async method would "queue" tasks on the thread pool, giving priority (as it should) to kestrel threads. This was causing message loss as GELF chunks were not being sent within the 5 second time limit.  Given that, using the periodic batch sink will use a synchronous UDP client and a non periodic batch sink will use the asynchronous client. The idea here is that the periodic batch sink is already async in nature, so when   its timer fires to empty its queue, we should ensure all messages (and chunks) are sent in that round.

**Comment by justmara** [comment]
Thank you. I'm observing pretty similar scenario but without any _heavy load_ - at a rate of ~30-50 msg/second our web-nodes start to queue unsent messages, keeping'em in memory for some reason. There are no any connection issues or so, nor any errors in selflog. But messages keep buffering in application. They keep coming to graylog but at veeeeeeeeery slow rate. 
That's why I were asking. The funniest part is that it can send (and graylog can receive at that rate) thousands of messages/sec, but at some point it suddenly becomes to *lag*.

**Comment by Aenima4six2** [comment]
@justmara Try using the non periodic batch sink implementation or reduce the `Period` property in `GraylogSinkOptions ` for the periodic sink

**Pull request merged**
